// app/api/seed/route.ts
// Seeds the database with sample products for all 4 categories.
// POST /api/seed  →  inserts sample data (skips existing rows via onConflict: ignore)
// Only works when SUPABASE_SERVICE_ROLE_KEY is present.

import { NextResponse } from "next/server";
import { createServiceRoleClient } from "@/supabase/server";
import type { Database } from "@/types/database";

type GadgetInsert     = Database["public"]["Tables"]["gadgets"]["Insert"];
type JerseyInsert     = Database["public"]["Tables"]["jerseys"]["Insert"];
type CarInsert        = Database["public"]["Tables"]["cars"]["Insert"];
type RealEstateInsert = Database["public"]["Tables"]["real_estates"]["Insert"];

const GADGETS: GadgetInsert[] = [
  {
    id: "g-001",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    type: "phone",
    price: 1250000,
    image_url: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80",
    description: "Latest Apple flagship with A17 Pro chip, titanium frame, and 48MP camera system.",
    condition: "Brand New",
    specs: { Storage: "256GB", RAM: "8GB", Display: "6.7 inch Super Retina XDR", Battery: "4422mAh" },
    stock: 15,
    is_active: true,
  },
  {
    id: "g-002",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    type: "phone",
    price: 1150000,
    image_url: "https://images.unsplash.com/photo-1707195099834-1e2b8e2f6e0d?w=600&q=80",
    description: "Samsung's most powerful phone with built-in S Pen and 200MP camera.",
    condition: "Brand New",
    specs: { Storage: "512GB", RAM: "12GB", Display: "6.8 inch Dynamic AMOLED", Battery: "5000mAh" },
    stock: 10,
    is_active: true,
  },
  {
    id: "g-003",
    name: 'MacBook Pro 14"',
    brand: "Apple",
    type: "laptop",
    price: 2400000,
    image_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80",
    description: "Powerful laptop with M3 Pro chip, Liquid Retina XDR display, and 22-hour battery.",
    condition: "Brand New",
    specs: { Chip: "Apple M3 Pro", RAM: "18GB", Storage: "512GB SSD", Display: "14.2 inch Liquid Retina XDR" },
    stock: 8,
    is_active: true,
  },
  {
    id: "g-004",
    name: "PlayStation 5",
    brand: "Sony",
    type: "game",
    price: 580000,
    image_url: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&q=80",
    description: "Next-gen gaming console with ultra-high speed SSD and 4K gaming at 120fps.",
    condition: "Brand New",
    specs: { CPU: "AMD Zen 2", GPU: "10.28 TFLOPS", Storage: "825GB NVMe SSD", Resolution: "Up to 8K" },
    stock: 5,
    is_active: true,
  },
  {
    id: "g-005",
    name: "iPad Pro 12.9",
    brand: "Apple",
    type: "tablet",
    price: 920000,
    image_url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80",
    description: "Pro-grade tablet with M2 chip, Liquid Retina XDR display and Apple Pencil support.",
    condition: "Brand New",
    specs: { Chip: "Apple M2", RAM: "8GB", Storage: "256GB", Display: "12.9 inch Liquid Retina XDR" },
    stock: 12,
    is_active: true,
  },
  {
    id: "g-006",
    name: "AirPods Pro 2nd Gen",
    brand: "Apple",
    type: "accessory",
    price: 195000,
    image_url: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
    description: "Active noise cancellation, Adaptive Transparency, and Personalized Spatial Audio.",
    condition: "Brand New",
    specs: { "ANC": "Active Noise Cancellation", "Battery": "6hr + 24hr case", Chip: "H2", Connectivity: "Bluetooth 5.3" },
    stock: 30,
    is_active: true,
  },
  {
    id: "g-007",
    name: "Dell XPS 15",
    brand: "Dell",
    type: "laptop",
    price: 1650000,
    image_url: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",
    description: "Premium Windows laptop with OLED display, Intel Core i7 and RTX 4060.",
    condition: "Brand New",
    specs: { CPU: "Intel Core i7-13700H", GPU: "NVIDIA RTX 4060", RAM: "16GB DDR5", Storage: "1TB NVMe SSD" },
    stock: 6,
    is_active: true,
  },
  {
    id: "g-008",
    name: "iPhone 13 (Used)",
    brand: "Apple",
    type: "phone",
    price: 480000,
    image_url: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=600&q=80",
    description: "Excellent condition iPhone 13 with A15 Bionic, dual-camera system. Minor scratches on back.",
    condition: "Used - Like New",
    specs: { Storage: "128GB", RAM: "4GB", Display: "6.1 inch Super Retina XDR", Battery: "3227mAh" },
    stock: 3,
    is_active: true,
  },
];

const JERSEYS: JerseyInsert[] = [
  {
    id: "j-001",
    name: "Real Madrid Home 2024/25",
    team: "Real Madrid",
    type: "club",
    category: "current",
    price: 45000,
    image_url: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&q=80",
    description: "Official Real Madrid home jersey for the 2024/25 La Liga season.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    season: "2024/25",
    stock: 50,
    is_active: true,
  },
  {
    id: "j-002",
    name: "Nigeria Super Eagles Away",
    team: "Nigeria",
    type: "country",
    category: "current",
    price: 38000,
    image_url: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&q=80",
    description: "Nigeria national team away jersey. Show your pride for the Super Eagles!",
    sizes: ["S", "M", "L", "XL"],
    season: "2024",
    stock: 40,
    is_active: true,
  },
  {
    id: "j-003",
    name: "Manchester City Home 2024/25",
    team: "Manchester City",
    type: "club",
    category: "current",
    price: 42000,
    image_url: "https://images.unsplash.com/photo-1518604666860-9ed391f76460?w=600&q=80",
    description: "Official Man City home jersey. City blue with the classic badge.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    season: "2024/25",
    stock: 35,
    is_active: true,
  },
  {
    id: "j-004",
    name: "Los Angeles Lakers #23",
    team: "Los Angeles Lakers",
    type: "basketball",
    category: "current",
    price: 52000,
    image_url: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&q=80",
    description: "Lakers iconic gold and purple jersey. LeBron James #23 edition.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    season: "2024/25",
    stock: 20,
    is_active: true,
  },
  {
    id: "j-005",
    name: "Kansas City Chiefs #15",
    team: "Kansas City Chiefs",
    type: "nfl",
    category: "current",
    price: 58000,
    image_url: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=600&q=80",
    description: "Patrick Mahomes #15 Chiefs home jersey. Super Bowl Champions edition.",
    sizes: ["S", "M", "L", "XL"],
    season: "2024",
    stock: 18,
    is_active: true,
  },
  {
    id: "j-006",
    name: "Barcelona Retro 1999",
    team: "FC Barcelona",
    type: "retro",
    category: "retro",
    price: 35000,
    image_url: "https://images.unsplash.com/photo-1564415637254-92c66292cd64?w=600&q=80",
    description: "Iconic Blaugrana stripes from the treble-winning 1998/99 season.",
    sizes: ["M", "L", "XL"],
    season: "1998/99",
    stock: 12,
    is_active: true,
  },
  {
    id: "j-007",
    name: "Chelsea Away 2024/25",
    team: "Chelsea FC",
    type: "club",
    category: "current",
    price: 40000,
    image_url: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&q=80",
    description: "Chelsea FC away jersey in yellow. Sharp, clean design for 2024/25.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    season: "2024/25",
    stock: 28,
    is_active: true,
  },
  {
    id: "j-008",
    name: "Brazil Home Copa América",
    team: "Brazil",
    type: "country",
    category: "current",
    price: 41000,
    image_url: "https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=600&q=80",
    description: "Brazil national team home jersey — the iconic Seleção yellow and green.",
    sizes: ["S", "M", "L", "XL"],
    season: "2024",
    stock: 32,
    is_active: true,
  },
];

const CARS: CarInsert[] = [
  {
    id: "c-001",
    name: "Toyota Camry 2022",
    brand: "Toyota",
    model: "Camry",
    year: 2022,
    price: 18500000,
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&q=80",
    description: "Clean Tokunbo Toyota Camry. Full customs duty paid. Excellent Nigerian roads condition.",
    mileage: "42,000 km",
    condition: "Used - Like New",
    fuel_type: "Petrol",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
  {
    id: "c-002",
    name: "Mercedes-Benz C300 2021",
    brand: "Mercedes-Benz",
    model: "C300",
    year: 2021,
    price: 32000000,
    image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&q=80",
    description: "Tokunbo Mercedes C300. Well maintained, full service history. Lagos registered.",
    mileage: "38,000 km",
    condition: "Used - Excellent",
    fuel_type: "Petrol",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
  {
    id: "c-003",
    name: "Honda Accord 2020",
    brand: "Honda",
    model: "Accord",
    year: 2020,
    price: 14500000,
    image_url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=80",
    description: "Foreign used Honda Accord Sport edition. Accident free, clean title.",
    mileage: "55,000 km",
    condition: "Used - Good",
    fuel_type: "Petrol",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
  {
    id: "c-004",
    name: "Lexus RX 350 2023",
    brand: "Lexus",
    model: "RX 350",
    year: 2023,
    price: 52000000,
    image_url: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&q=80",
    description: "Brand new Lexus RX 350 F Sport. Never used, straight from dealer.",
    mileage: "0 km",
    condition: "Brand New",
    fuel_type: "Petrol",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
  {
    id: "c-005",
    name: "Ford Ranger 2021",
    brand: "Ford",
    model: "Ranger",
    year: 2021,
    price: 19800000,
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    description: "Foreign used Ford Ranger pickup. Perfect for Lagos and off-road terrain.",
    mileage: "61,000 km",
    condition: "Used - Good",
    fuel_type: "Diesel",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
  {
    id: "c-006",
    name: "BMW 3 Series 2022",
    brand: "BMW",
    model: "3 Series",
    year: 2022,
    price: 28500000,
    image_url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80",
    description: "Tokunbo BMW 330i M Sport. Loaded with options, beautiful condition.",
    mileage: "30,000 km",
    condition: "Used - Like New",
    fuel_type: "Petrol",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
  {
    id: "c-007",
    name: "Toyota Corolla 2019",
    brand: "Toyota",
    model: "Corolla",
    year: 2019,
    price: 10500000,
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=600&q=80",
    description: "Nigerian used Toyota Corolla. Very clean, regularly serviced at Toyota dealer.",
    mileage: "88,000 km",
    condition: "Used - Good",
    fuel_type: "Petrol",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
  {
    id: "c-008",
    name: "Range Rover Sport 2022",
    brand: "Land Rover",
    model: "Range Rover Sport",
    year: 2022,
    price: 85000000,
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&q=80",
    description: "Foreign used Range Rover Sport HSE. Panoramic roof, all options included.",
    mileage: "22,000 km",
    condition: "Used - Like New",
    fuel_type: "Petrol",
    transmission: "Automatic",
    is_available: true,
    seller_id: null,
  },
];

const REAL_ESTATES: RealEstateInsert[] = [
  {
    id: "re-001",
    name: "3 Bedroom Flat — Lekki Phase 1",
    type: "apartment",
    location: "Lekki Phase 1, Lagos",
    price: 85000000,
    image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
    description: "Spacious 3-bedroom flat in prime Lekki Phase 1 location. Fully tiled, prepaid meter, 24/7 security.",
    size: "180",
    bedrooms: 3,
    bathrooms: 3,
    features: ["Prepaid Meter", "24/7 Security", "Parking Space", "Backup Generator", "Swimming Pool"],
    is_available: true,
    seller_id: null,
  },
  {
    id: "re-002",
    name: "5 Bedroom Duplex — Ikoyi",
    type: "house",
    location: "Ikoyi, Lagos",
    price: 450000000,
    image_url: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600&q=80",
    description: "Luxurious 5-bedroom fully detached duplex in Ikoyi. Smart home system, BQ included.",
    size: "450",
    bedrooms: 5,
    bathrooms: 6,
    features: ["Smart Home", "Swimming Pool", "BQ", "Gym", "Cinema Room", "4 Parking Spaces"],
    is_available: true,
    seller_id: null,
  },
  {
    id: "re-003",
    name: "Commercial Plot — Victoria Island",
    type: "land",
    location: "Victoria Island, Lagos",
    price: 650000000,
    image_url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80",
    description: "Prime commercial land on VI. C of O available. Perfect for office building or mixed-use development.",
    size: "1200",
    bedrooms: null,
    bathrooms: null,
    features: ["C of O", "Corner Piece", "Road Frontage", "Fenced"],
    is_available: true,
    seller_id: null,
  },
  {
    id: "re-004",
    name: "2 Bedroom Apartment — Ikeja GRA",
    type: "apartment",
    location: "Ikeja GRA, Lagos",
    price: 45000000,
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
    description: "Modern 2-bedroom apartment in Ikeja GRA. Serviced, fully furnished available on request.",
    size: "120",
    bedrooms: 2,
    bathrooms: 2,
    features: ["Serviced", "CCTV", "Backup Generator", "Parking"],
    is_available: true,
    seller_id: null,
  },
  {
    id: "re-005",
    name: "4 Bedroom Terrace — Chevron",
    type: "house",
    location: "Chevron Drive, Lagos",
    price: 120000000,
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    description: "Newly built 4-bedroom terrace house in a gated estate off Chevron Drive.",
    size: "280",
    bedrooms: 4,
    bathrooms: 5,
    features: ["Gated Estate", "Borehole", "Solar Power", "Gym", "Children Playground"],
    is_available: true,
    seller_id: null,
  },
  {
    id: "re-006",
    name: "Office Space — Adeola Odeku",
    type: "commercial",
    location: "Adeola Odeku, Victoria Island, Lagos",
    price: 180000000,
    image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    description: "Grade A office space on Adeola Odeku. Open plan, 3 floors available, central AC.",
    size: "600",
    bedrooms: null,
    bathrooms: 4,
    features: ["Central AC", "3 Phase Power", "Lifts", "CCTV", "Reception"],
    is_available: true,
    seller_id: null,
  },
  {
    id: "re-007",
    name: "Residential Land — Abijo GRA",
    type: "land",
    location: "Abijo GRA, Lagos",
    price: 22000000,
    image_url: "https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=600&q=80",
    description: "Dry land in Abijo GRA with proper documentation. Suitable for residential building.",
    size: "500",
    bedrooms: null,
    bathrooms: null,
    features: ["Survey Plan", "Gazette", "Road Access", "Dry Land"],
    is_available: true,
    seller_id: null,
  },
  {
    id: "re-008",
    name: "Studio Apartment — Yaba",
    type: "apartment",
    location: "Yaba, Lagos",
    price: 18000000,
    image_url: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=600&q=80",
    description: "Modern studio apartment in the heart of Yaba tech district. Perfect for young professionals.",
    size: "65",
    bedrooms: 1,
    bathrooms: 1,
    features: ["Fibre Internet", "Rooftop Terrace", "Co-working Space", "Backup Power"],
    is_available: true,
    seller_id: null,
  },
];

export async function POST() {
  try {
    const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
    if (!serviceKey) {
      return NextResponse.json({ success: false, error: "SUPABASE_SERVICE_ROLE_KEY not set" }, { status: 400 });
    }

    const supabase = createServiceRoleClient();
    const results: Record<string, unknown> = {};

    // Seed gadgets
    const { error: gErr } = await supabase.from("gadgets").upsert(GADGETS, { onConflict: "id", ignoreDuplicates: false });
    results.gadgets = gErr ? `Error: ${gErr.message}` : `${GADGETS.length} rows upserted`;

    // Seed jerseys
    const { error: jErr } = await supabase.from("jerseys").upsert(JERSEYS, { onConflict: "id", ignoreDuplicates: false });
    results.jerseys = jErr ? `Error: ${jErr.message}` : `${JERSEYS.length} rows upserted`;

    // Seed cars (seller_id must be null or a valid uuid)
    const carsWithoutSeller = CARS.map(({ seller_id: _s, ...rest }) => rest);
    const { error: cErr } = await supabase.from("cars").upsert(carsWithoutSeller, { onConflict: "id", ignoreDuplicates: false });
    results.cars = cErr ? `Error: ${cErr.message}` : `${CARS.length} rows upserted`;

    // Seed real_estates
    const estatesWithoutSeller = REAL_ESTATES.map(({ seller_id: _s, ...rest }) => rest);
    const { error: rErr } = await supabase.from("real_estates").upsert(estatesWithoutSeller, { onConflict: "id", ignoreDuplicates: false });
    results.realestate = rErr ? `Error: ${rErr.message}` : `${REAL_ESTATES.length} rows upserted`;

    const hasErrors = Object.values(results).some((v) => typeof v === "string" && v.startsWith("Error:"));

    return NextResponse.json({
      success: !hasErrors,
      message: hasErrors ? "Some tables failed — check results" : "All tables seeded successfully! 🎉",
      results,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({
    message: "Send a POST request to this endpoint to seed the database with sample products.",
    tables: ["gadgets (8 items)", "jerseys (8 items)", "cars (8 items)", "real_estates (8 items)"],
    note: "Requires SUPABASE_SERVICE_ROLE_KEY in .env.local",
  });
}
